### ISSUE TITLE
Checkout GRAV

### ISSUE THREAD

**Issue by mdrmike** [Ajedi32/metalsmith-metafiles#1]
Heya, not sure how to message you using github... I saw [this metalsmith issue](https://github.com/segmentio/metalsmith/issues/157#issuecomment-142124072) from your mention on [this Jekyll Issue (with linting)](https://github.com/jekyll/jekyll/issues/3408#issuecomment-118405381)

Thought I'd suggest you look at:  [GRAV](https://github.com/getgrav/grav)

It's not (currently) a static site generator -- but its database-less, meaning some yaml files.  Only requirement is PHP5.4.  Its also very plugablle like **metalsmith.**  In fact, no editing on the server by default, without a plugin.  That said, its likely very easy to turn it into a static-site-generator with a plugin.  Just thought I'd share.  FWIW, they're using [gitter](http://gitter.im/) for communication.

**Comment by Ajedi32** [comment]
Thanks, GRAV looks really nice. Unfortunately I think I may already be hooked on Metalsmith :wink:.

I kind of already mentioned this in that Metalsmith issue you linked, but the sheer simplicity of Metalsmith's API really sold me on the whole platform. I was able to understand the entire system with only a couple minutes of reading! Not to mention that I can write a simple plugin in one line of code.

As far as the whole frontmatter problem goes, I am a bit annoyed that Metalsmith has that built-in rather than in a plugin, but I can turn it off with one line of code anyway so it's not really a big deal.
